// Generated by @moltcms/static. Do not edit.
import type { SchemaVersionIndex } from "@moltcms/client";

export interface MoltcmsSchemas {
	post: {
		1: {
			title: string;
			slug: string;
			body?: string | null;
		};
	};
}

export const schemaVersions = {
	post: [1],
} as const satisfies SchemaVersionIndex<MoltcmsSchemas>;

export const schemaFingerprint = "fixture-schema-v1";
