#!/usr/bin/env node

import { writeFile } from "node:fs/promises";
import { pathToFileURL } from "node:url";
import { fetchSyncSchemas } from "./schema-client.js";
import type { ContentSchema, FieldDef } from "./types.js";

/** Renders an importable TypeScript schema map from moltcms schema metadata. */
export function generateSchemaTypes(schemas: readonly ContentSchema[]): string {
	const ordered = [...schemas].sort(
		(left, right) =>
			left.content_type.localeCompare(right.content_type) ||
			left.version - right.version,
	);
	const grouped = Object.groupBy(ordered, (schema) => schema.content_type);
	const blocks = Object.entries(grouped)
		.sort(([left], [right]) => left.localeCompare(right))
		.map(
			([contentType, versions]) =>
				`\t${JSON.stringify(contentType)}: {\n${(versions ?? []).map((schema) => `\t\t${schema.version}: {\n${schema.fields.map(renderField).join("\n")}\n\t\t};`).join("\n")}\n\t};`,
		)
		.join("\n");
	const schemaVersions = Object.fromEntries(
		Object.entries(grouped).map(([contentType, versions]) => [
			contentType,
			(versions ?? []).map((schema) => schema.version),
		]),
	);
	return `// Generated by @moltcms-sdk/client. Do not edit.\nimport type { SchemaVersionIndex } from "@moltcms-sdk/client";\n\nexport interface MoltcmsSchemas {\n${blocks}\n}\n\nexport const schemaVersions = ${JSON.stringify(schemaVersions, null, "\t")} as const satisfies SchemaVersionIndex<MoltcmsSchemas>;\n`;
}
function renderField(field: FieldDef): string {
	const required = field.required ? "" : "?";
	return `\t\t\t${JSON.stringify(field.name)}${required}: ${renderFieldValue(field)}${field.required ? "" : " | null"};`;
}
function renderFieldValue(field: FieldDef): string {
	switch (field.kind) {
		case "string":
		case "text":
		case "datetime":
			return "string";
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		case "image":
		case "relation":
			return field.multiple ? "string[]" : "string";
		case "select": {
			const values =
				field.options.map((option) => JSON.stringify(option)).join(" | ") ||
				"never";
			return field.multiple ? `(${values})[]` : values;
		}
		case "richtext":
		case "json":
			return "unknown";
	}
}
async function main(): Promise<void> {
	const values = new Map<string, string>();
	for (let index = 0; index < process.argv.length - 1; index += 2) {
		const option = process.argv.slice(2)[index];
		const value = process.argv.slice(2)[index + 1];
		if (option?.startsWith("--") && value !== undefined)
			values.set(option.slice(2), value);
	}
	const syncUrl = values.get("sync-url");
	const apiKey = values.get("api-key");
	const output = values.get("output");
	if (syncUrl === undefined || apiKey === undefined || output === undefined)
		throw new TypeError(
			"Usage: moltcms-sdk-codegen --sync-url <url> --api-key <key> --output <file>",
		);
	await writeFile(
		output,
		generateSchemaTypes(await fetchSyncSchemas(syncUrl, { apiKey })),
	);
}
if (
	process.argv[1] !== undefined &&
	import.meta.url === pathToFileURL(process.argv[1]).href
)
	main().catch((error: unknown) => {
		console.error(error);
		process.exitCode = 1;
	});
